---
abstract: 'Thin fast full interface to the libmemcached client API'
author:
  - 'Tim Bunce <Tim.Bunce@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Memcached-libmemcached
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
version: 1.001701
