--- #YAML:1.0
name:                Memcached-libmemcached
version:             0.1304
abstract:            Thin fast full interface to the libmemcached client API
license:             ~
author:              
    - Tim Bunce <Tim.Bunce@pobox.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    perl:                          5.006
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
